# The BUILD rules for webrtc chrome implementation and related module.

package(default_visibility = ["//visibility:public"])
 	 	
cc_library(
  name = "include",
  srcs = [
         ],
  hdrs = [
          "module_common_types.h",
          "module.h"
         ],
  deps = [
          "//third_party/glog",
          "//stream_service/orbit/webrtc:webrtc_common",
          "//stream_service/orbit/webrtc/common_video:common_video"
          
         ],
)
