# The BUILD rules for voice/audio related processing module.

package(default_visibility = ["//visibility:public"])

cc_library(
  name = "audio_energy",
  srcs = [
          "audio_energy.cc",
         ],
  hdrs = [
          "audio_energy.h",
         ],
  deps = [
          "//third_party/glog"
         ],
)
