# The BUILD rules for webrtc chrome implementation and related module.

package(default_visibility = ["//visibility:public"])
 	 	
cc_library(
  name = "common_video",
  srcs = [
         ],
  hdrs = [
          "rotation.h",
         ],
  deps = [
          "//third_party/glog",
          "//stream_service/orbit/webrtc/base:rtc_base"
         ],
)
